---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-application
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: application
