---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-main
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: web
      port: 8080
  selector:
    app: {{ .Chart.Name }}-{{ .Values.environment }}-main
    service: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}-main-np
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: jnlp
      port: 30000
      nodePort: 30000
  selector:
    app: {{ .Chart.Name }}-{{ .Values.environment }}-main
    service: jenkins
