---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}
data:
  github_token: {{ .Values.config.github.token | b64enc }}
  github_secret: {{ .Values.config.github.secret | b64enc }}
