---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}
spec:
  ports:
    - name: web
      port: 4141
  selector:
    app: {{ .Chart.Name }}-{{ .Values.environment }}
    service: atlantis
